//! **BiometricChart** — fast-oscillating multi-trace line chart (PRD §3 体征折线图).
//!
//! ## Spec
//! - Rapidly fluctuating compound line chart simulating heart rate, energy
//!   surges, or radiation index.
//!
//! ## Implementation notes
//! - Stateful [`StatefulWidget`]; per-trace rolling sample buffers live in
//!   [`BiometricChartState`], pushed each tick (or self-generated by `tick()`).
//! - Rendered with ratatui `Chart` + one `Dataset` per trace
//!   (`Marker::Braille`, `GraphType::Line`), `x_bounds = [0, window]`,
//!   `y_bounds = [0, 100]`. Colors come from the theme's CSS cascade, not the
//!   raw palette: the axes and chart block use the base `Biometric` node
//!   (`.fg` = muted, `.bg` = panel), and each trace's color is resolved via
//!   the `Biometric.trace0..4` rules (same mapping as before):
//!     - trace 0 → `Biometric.trace0` (var `--accent`)
//!     - trace 1 → `Biometric.trace1` (var `--accent2`)
//!     - trace 2 → `Biometric.trace2` (var `--ok`)
//!     - trace 3 → `Biometric.trace3` (var `--warn`)
//!     - trace ≥4 → `Biometric.trace4` (var `--alert`, the fallback)
//! - Two data-feed modes:
//!     1. **External**: the app calls [`BiometricChartState::push`] to feed
//!        live samples per trace.
//!     2. **Self-generated (demo mode)**: if no external data is pushed, the
//!        app calls [`BiometricChartState::tick`] each frame and the state
//!        advances its own deterministic oscillator (a different frequency per
//!        trace, heart-rate-like). The demo uses this mode.
//!
//! # Example
//!
//! ```no_run
//! use ratatui_sci_fi::{BiometricChart, BiometricChartState, Theme};
//!
//! let mut state = BiometricChartState::new(3, 80);
//! let chart = BiometricChart::new(3).window(80).theme(Theme::Cyberpunk);
//! // In the event loop: state.tick(); each frame, then render the chart.
//! ```

use ratatui::{
    buffer::Buffer,
    layout::Rect,
    style::Style,
    symbols::Marker,
    widgets::{Axis, Block, Chart, Dataset, GraphType, StatefulWidget, Widget},
};
use ratatui_style::{ComputeScratch, NodeRef};

use crate::Theme;

/// Y-axis value range the chart is drawn against. Samples are clamped to it.
const Y_MIN: f64 = 0.0;
const Y_MAX: f64 = 100.0;

/// A multi-trace biometric waveform (PRD §3 体征折线图).
///
/// Immutable config lives here (`traces`, `window`, `theme`); everything that
/// changes per frame lives in [`BiometricChartState`].
#[derive(Debug, Clone)]
pub struct BiometricChart {
    /// Number of traces (independent waveforms) to draw.
    pub traces: usize,
    /// Horizontal sample-window width (number of points kept per trace).
    pub window: usize,
    /// Active theme; controls all colors via its [`Palette`] and CSS cascade.
    pub theme: Theme,
}

impl Default for BiometricChart {
    fn default() -> Self {
        Self { traces: 3, window: 80, theme: Theme::default() }
    }
}

impl BiometricChart {
    /// Build a chart with the given number of traces.
    pub fn new(traces: usize) -> Self {
        Self::default().traces(traces)
    }

    /// Set the number of traces (clamped to at least 1). Builder.
    #[must_use]
    pub fn traces(mut self, traces: usize) -> Self {
        self.traces = traces.max(1);
        self
    }

    /// Set the sample-window width (clamped to at least 2). Builder.
    #[must_use]
    pub fn window(mut self, window: usize) -> Self {
        self.window = window.max(2);
        self
    }

    /// Replace the theme (builder). Default is [`Theme::Cyberpunk`].
    #[must_use]
    pub fn theme(mut self, theme: Theme) -> Self {
        self.theme = theme;
        self
    }
}

/// Mutable state for [`BiometricChart`].
///
/// Holds a rolling sample buffer per trace (length capped at `window`) plus a
/// tick counter that drives the self-generated oscillator. The app advances it
/// every frame via [`Self::tick`] (demo mode) or feeds live samples via
/// [`Self::push`] (external mode).
#[derive(Debug, Clone)]
pub struct BiometricChartState {
    /// Per-trace rolling sample buffers; each `Vec<f64>` holds the most recent
    /// up-to-`window` samples, oldest first.
    buffers: Vec<Vec<f64>>,
    /// Configured window length (max samples kept per trace).
    window: usize,
    /// Animation clock, advanced each tick; used by the self-generated
    /// oscillator when no external data is pushed.
    tick: u64,
}

impl Default for BiometricChartState {
    fn default() -> Self {
        Self::new(3, 80)
    }
}

impl BiometricChartState {
    /// Build state sized for `traces` traces and a `window`-sample rolling
    /// buffer. Buffers start seeded with a baseline so the chart isn't empty
    /// on the first frame.
    pub fn new(traces: usize, window: usize) -> Self {
        let traces = traces.max(1);
        let window = window.max(2);
        // Seed each buffer with one baseline sample at mid-range so the first
        // render has at least one point per trace to plot.
        let baseline = (Y_MIN + Y_MAX) / 2.0;
        let buffers = (0..traces).map(|_| vec![baseline]).collect();
        Self { buffers, window, tick: 0 }
    }

    /// Feed a live sample for `trace_index` (external-feed mode).
    ///
    /// The value is clamped to `[Y_MIN, Y_MAX]` and appended to that trace's
    /// rolling buffer; the oldest sample is dropped once the buffer exceeds
    /// `window`. Out-of-range indices are ignored.
    pub fn push(&mut self, trace_index: usize, value: f64) {
        let Some(buf) = self.buffers.get_mut(trace_index) else {
            return;
        };
        let clamped = value.clamp(Y_MIN, Y_MAX);
        // Cap the rolling window.
        crate::widgets::util::capped_push(buf, clamped, self.window);
    }

    /// Advance the waveform by one tick.
    ///
    /// In **demo / self-generated mode** (when the app does not call
    /// [`Self::push`]), this computes the next oscillating sample for every
    /// trace — a sum of sines with a different base frequency per trace,
    /// giving a heart-rate / energy / radiation-like fast-fluctuating
    /// waveform — and pushes it into each rolling buffer. The app should call
    /// this once per frame.
    pub fn tick(&mut self) {
        self.tick = self.tick.wrapping_add(1);
        let t = self.tick as f64;
        for (i, buf) in self.buffers.iter_mut().enumerate() {
            let value = Self::oscillator(i, t);
            crate::widgets::util::capped_push(buf, value, self.window);
        }
    }

    /// Deterministic per-trace oscillator producing a value in `[Y_MIN, Y_MAX]`.
    ///
    /// Each trace gets a distinct base frequency; a couple of harmonics plus a
    /// slow drift create the irregular, vital-signs-like shape.
    fn oscillator(trace: usize, t: f64) -> f64 {
        // Distinct base angular frequency per trace (radians/sample).
        let base = 0.35 + 0.18 * (trace as f64 + 1.0);
        // Phase offset so traces don't align.
        let phase = (trace as f64) * 0.9;
        // Two harmonics + a slow drift, normalized to roughly [-1, 1].
        let raw = (base * t + phase).sin() * 0.6
            + (base * 2.3 * t + phase).sin() * 0.25
            + (0.05 * t + phase).sin() * 0.15;
        // Map [-1, 1] → [Y_MIN, Y_MAX] and clamp for safety.
        let mapped = (Y_MIN + Y_MAX) / 2.0 + raw * ((Y_MAX - Y_MIN) / 2.0);
        mapped.clamp(Y_MIN, Y_MAX)
    }

    /// Current tick counter (mainly useful for tests / diagnostics).
    pub fn tick_count(&self) -> u64 {
        self.tick
    }
}

impl StatefulWidget for BiometricChart {
    type State = BiometricChartState;

    fn render(self, area: Rect, buf: &mut Buffer, state: &mut Self::State) {
        // Guard zero-size areas — nothing to draw.
        if area.width == 0 || area.height == 0 {
            return;
        }

        // Resolve all colors from the theme's CSS cascade. The base
        // `Biometric` node carries the axis foreground (muted) and the chart
        // block background (panel); per-trace colors come from the
        // `Biometric.traceN` rules (trace ≥5 falls back to trace4).
        let sheet = self.theme.stylesheet();
        let mut scratch = ComputeScratch::new();
        let base_style = sheet
            .compute_with(&NodeRef::new("Biometric"), None, &mut scratch)
            .to_style();
        let axis_style = Style::default().fg(base_style.fg.unwrap());
        let block_bg = base_style.bg.unwrap();

        // Pre-collect each trace's `(x, y)` points as `f64` pairs. The `Chart`
        // borrows `&[(f64, f64)]`, so the vectors must outlive the render.
        let window_f = self.window as f64;
        let mut per_trace_points: Vec<Vec<(f64, f64)>> = Vec::with_capacity(self.traces);
        for i in 0..self.traces {
            let buf_i = state.buffers.get(i);
            let pts: Vec<(f64, f64)> = match buf_i {
                Some(samples) if !samples.is_empty() => {
                    // Spread the samples evenly across [0, window]. If fewer
                    // than `window` samples are present, right-align them so
                    // the waveform scrolls in from the right.
                    let n = samples.len();
                    let start = window_f - (n as f64 - 1.0).max(0.0) - 1.0;
                    let step = 1.0; // one column per sample
                    samples
                        .iter()
                        .enumerate()
                        .map(|(idx, &v)| (start + (idx as f64) * step, v))
                        .collect()
                }
                _ => Vec::new(),
            };
            per_trace_points.push(pts);
        }

        // Build one Dataset per trace, styling each from its `traceN` cascade
        // rule. Clamp the index to 4 so trace ≥5 falls back to trace4 (alert),
        // matching the previous default.
        let datasets: Vec<Dataset<'_>> = (0..self.traces)
            .map(|i| {
                let cls = format!("trace{}", i.min(4));
                let trace_style = sheet
                    .compute_with(&NodeRef::new("Biometric").classes(&[&cls]), None, &mut scratch)
                    .to_style();
                let name = format!("ch{}", i);
                let pts = &per_trace_points[i];
                Dataset::default()
                    .name(name)
                    .data(pts)
                    .marker(Marker::Braille)
                    .graph_type(GraphType::Line)
                    .style(trace_style)
            })
            .collect();

        let x_axis = Axis::default()
            .bounds([0.0, window_f])
            .labels(["0".to_string(), self.window.to_string()])
            .style(axis_style);

        let y_axis = Axis::default()
            .bounds([Y_MIN, Y_MAX])
            .labels(["0", "50", "100"])
            .style(axis_style);

        let chart = Chart::new(datasets)
            .block(Block::new().title("BIOMETRICS"))
            .style(Style::default().bg(block_bg))
            .x_axis(x_axis)
            .y_axis(y_axis);

        // `Chart: Widget`, render by value.
        chart.render(area, buf);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ratatui::layout::Rect;

    /// Helper: render the chart into a fresh buffer and return it.
    fn render(
        traces: usize,
        window: usize,
        theme: Theme,
        ticks: u64,
        width: u16,
        height: u16,
    ) -> (Buffer, BiometricChartState) {
        let mut buf = Buffer::empty(Rect::new(0, 0, width, height));
        let widget = BiometricChart::new(traces).window(window).theme(theme);
        let mut state = BiometricChartState::new(traces, window);
        for _ in 0..ticks {
            state.tick();
        }
        StatefulWidget::render(widget, Rect::new(0, 0, width, height), &mut buf, &mut state);
        (buf, state)
    }

    /// True if the buffer has at least one non-space, non-blank cell.
    fn buffer_has_content(buf: &Buffer) -> bool {
        buf.content.iter().any(|c| c.symbol() != " ")
    }

    #[test]
    fn renders_without_panicking_after_ticks() {
        // Drive the oscillator for a while, then render into a modest area.
        let (buf, _) = render(3, 80, Theme::Cyberpunk, 40, 60, 16);
        // Chart should produce *some* non-blank cells (axes, title, trace).
        assert!(buffer_has_content(&buf), "expected non-blank cells after rendering");
    }

    #[test]
    fn tick_advances_clock_and_buffers() {
        let mut state = BiometricChartState::new(2, 10);
        let before = state.tick_count();
        state.tick();
        assert_eq!(state.tick_count(), before + 1);
        // After one tick each trace buffer grew by exactly one sample.
        // (Buffers start seeded with one baseline sample.)
    }

    #[test]
    fn push_clamps_and_caps_window() {
        let mut state = BiometricChartState::new(1, 4);
        // Values outside the range are clamped into [0, 100].
        state.push(0, 999.0);
        state.push(0, -50.0);
        assert_eq!(state.buffers[0].last().copied(), Some(Y_MIN));
        // Overflow beyond the window is trimmed.
        state.push(0, 10.0);
        state.push(0, 20.0);
        state.push(0, 30.0);
        assert!(state.buffers[0].len() <= 4, "rolling buffer must respect the window cap");
    }

    #[test]
    fn push_ignores_out_of_range_trace() {
        let mut state = BiometricChartState::new(2, 8);
        // trace index 5 doesn't exist; this must not panic.
        state.push(5, 42.0);
        assert_eq!(state.buffers.len(), 2);
    }

    #[test]
    fn oscillator_stays_in_range() {
        for trace in 0..6_u32 {
            for t in 0..1000_u32 {
                let v = BiometricChartState::oscillator(trace as usize, t as f64);
                assert!(
                    (Y_MIN..=Y_MAX).contains(&v),
                    "oscillator out of range: trace={trace} t={t} v={v}"
                );
            }
        }
    }

    #[test]
    fn zero_area_does_not_panic() {
        let widget = BiometricChart::new(3).window(20).theme(Theme::DeepSpace);
        let mut state = BiometricChartState::new(3, 20);
        let mut buf = Buffer::empty(Rect::ZERO);
        // Must be a no-op, not a panic.
        StatefulWidget::render(widget, Rect::ZERO, &mut buf, &mut state);
    }

    #[test]
    fn render_across_many_ticks_does_not_panic() {
        // Smoke test: render repeatedly across ticks, ensuring stability.
        let mut state = BiometricChartState::new(3, 40);
        let mut buf = Buffer::empty(Rect::new(0, 0, 50, 12));
        for _ in 0..200 {
            state.tick();
            let widget = BiometricChart::new(3).window(40).theme(Theme::Fallout);
            StatefulWidget::render(widget, Rect::new(0, 0, 50, 12), &mut buf, &mut state);
        }
        assert!(buffer_has_content(&buf));
    }

    #[test]
    fn external_feed_renders_non_blank() {
        // External mode: push known samples instead of ticking.
        let mut buf = Buffer::empty(Rect::new(0, 0, 40, 10));
        let widget = BiometricChart::new(2).window(10).theme(Theme::Weyland);
        let mut state = BiometricChartState::new(2, 10);
        for v in [10.0_f64, 30.0, 50.0, 70.0, 90.0, 50.0, 20.0] {
            state.push(0, v);
            state.push(1, 100.0 - v);
        }
        StatefulWidget::render(widget, Rect::new(0, 0, 40, 10), &mut buf, &mut state);
        assert!(buffer_has_content(&buf), "externally-fed chart should render content");
    }

    #[test]
    fn theme_builder_changes_trace_color() {
        // Sanity: the `Biometric.trace0..1` cascade rules resolve to the same
        // RGB as the palette tokens they back (accent / accent2).
        use ratatui_style::{ComputeScratch, NodeRef};
        let sheet = Theme::Cyberpunk.stylesheet();
        let mut scratch = ComputeScratch::new();
        let accent = Theme::Cyberpunk.palette().accent.color();
        let trace0 = sheet
            .compute_with(&NodeRef::new("Biometric").classes(&["trace0"]), None, &mut scratch)
            .to_style()
            .fg
            .unwrap();
        assert_eq!(trace0, accent);
        let accent2 = Theme::Cyberpunk.palette().accent2.color();
        let trace1 = sheet
            .compute_with(&NodeRef::new("Biometric").classes(&["trace1"]), None, &mut scratch)
            .to_style()
            .fg
            .unwrap();
        assert_eq!(trace1, accent2);
    }
}
