//! **Sparkline** — compact single-value trend line (a lightweight counterpart to
//! [`BiometricChart`](crate::BiometricChart)).
//!
//! A small borderless braille sparkline: one rolling trace of samples in
//! `0.0..=1.0` drawn with ratatui's `Chart` + a single `Dataset`
//! (`Marker::Braille`, `GraphType` selected by [`SparkShape`]). The line's color
//! tints with the latest sample's level (nominal → warn → alert), so a spiking
//! reading reads as a warning at a glance. An optional right-aligned percentage
//! readout overlays the top-right cell.
//!
//! ## Spec
//! - `window`-sample rolling buffer of values in `0.0..=1.0`.
//! - Drawn via a borderless ratatui `Chart` with hidden axes (no titles / no
//!   labels) carrying only bounds: x `[0, window]`, y `[0, 1]` — a clean
//!   sparkline.
//! - Three shapes (see [`SparkShape`]): connected line (default), braille
//!   column bars, or braille scatter points. Colors stay on CSS; shape affects
//!   only the ratatui `GraphType`.
//!
//! ## Implementation notes
//! - Stateful [`StatefulWidget`]; the rolling sample buffer lives in
//!   [`SparklineState`], pushed each tick (or self-generated by `tick()`).
//! - Colors come from the theme's CSS cascade, not the raw palette. The line
//!   color is resolved by the latest sample's level —
//!   `Spark.ok`|`Spark.warn`|`Spark.alert` (falling back to
//!   `palette.ok`|`warn`|`alert`). The chart background / grid use the base
//!   `Spark` node and `Spark.grid`.
//! - One `ComputeScratch` is reused for the whole frame.
//!
//! # Example
//!
//! ```no_run
//! use ratatui_sci_fi::{Sparkline, SparklineState, Theme};
//!
//! let mut state = SparklineState::new(64);
//! let spark = Sparkline::new().window(64).theme(Theme::Cyberpunk);
//! // In the event loop: state.tick(); each frame, then render the widget.
//! ```

use ratatui::{
    buffer::Buffer,
    layout::Rect,
    style::Style,
    symbols::Marker,
    widgets::{Axis, Block, Chart, Dataset, GraphType, StatefulWidget, Widget},
};
use ratatui_style::{ComputeScratch, NodeRef};

use crate::Theme;

/// Visual form of a [`Sparkline`].
///
/// Selects the ratatui `GraphType` used by the single braille `Dataset`; colors
/// stay on the CSS cascade (`Spark` / `Spark.ok`|`Spark.warn`|`Spark.alert` /
/// `Spark.grid`), untouched by this enum. The [`SparkShape::Line`] default
/// gives the classic connected-line sparkline.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum SparkShape {
    /// Connected braille line (`Marker::Braille`, `GraphType::Line`) — the
    /// classic sparkline. This is the default.
    #[default]
    Line,
    /// Braille column bars / histogram (`Marker::Braille`, `GraphType::Bar`).
    Block,
    /// Braille scatter points (`Marker::Braille`, `GraphType::Scatter`).
    Dot,
}

impl SparkShape {
    /// The ratatui `GraphType` this variant maps to.
    #[must_use]
    pub const fn graph_type(self) -> GraphType {
        match self {
            Self::Line => GraphType::Line,
            Self::Block => GraphType::Bar,
            Self::Dot => GraphType::Scatter,
        }
    }
}

/// A compact single-trace braille sparkline.
///
/// Immutable config lives here (`window`, `shape`, `theme`, `show_value`);
/// everything that changes per frame lives in [`SparklineState`].
#[derive(Debug, Clone)]
pub struct Sparkline {
    /// Horizontal sample-window width (number of points kept). Default `64`.
    pub window: usize,
    /// Glyph-set form. Defaults to [`SparkShape::Line`].
    pub shape: SparkShape,
    /// Theme whose palette drives colors via the CSS cascade. Default
    /// [`Theme::Cyberpunk`].
    pub theme: Theme,
    /// Whether to overlay the latest value as a right-aligned readout in the
    /// top-right cell. Default `true`.
    pub show_value: bool,
}

impl Default for Sparkline {
    fn default() -> Self {
        Self {
            window: 64,
            shape: SparkShape::default(),
            theme: Theme::Cyberpunk,
            show_value: true,
        }
    }
}

impl Sparkline {
    /// Build a sparkline with default config (window 64, line shape).
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the sample-window width (clamped to at least 2). Builder.
    #[must_use]
    pub fn window(mut self, n: usize) -> Self {
        self.window = n.max(2);
        self
    }

    /// Set the glyph-set form (see [`SparkShape`]). Builder.
    #[must_use]
    pub fn shape(mut self, s: SparkShape) -> Self {
        self.shape = s;
        self
    }

    /// Set the theme whose palette drives colors. Builder.
    #[must_use]
    pub fn theme(mut self, t: Theme) -> Self {
        self.theme = t;
        self
    }

    /// Toggle the right-aligned value readout overlay. Builder.
    #[must_use]
    pub fn show_value(mut self, show: bool) -> Self {
        self.show_value = show;
        self
    }
}

/// Mutable state for [`Sparkline`].
///
/// Holds a rolling sample buffer (length capped at `window`) plus a tick counter
/// that drives the self-generated oscillator. The app advances it every frame
/// via [`Self::tick`] (demo mode) or feeds live samples via [`Self::push`]
/// (external mode).
#[derive(Debug, Clone)]
pub struct SparklineState {
    /// Rolling sample buffer; holds the most recent up-to-`window` samples,
    /// oldest first. Values are clamped to `0.0..=1.0`.
    samples: Vec<f64>,
    /// Configured window length (max samples kept).
    window: usize,
    /// Animation clock, advanced each tick; used by the self-generated
    /// oscillator when no external data is pushed.
    tick_count: u64,
}

impl Default for SparklineState {
    fn default() -> Self {
        Self::new(64)
    }
}

impl SparklineState {
    /// Build state with a `window`-sample rolling buffer (clamped to at least
    /// 2). The buffer starts seeded with one mid baseline (`0.5`) sample so the
    /// first render has at least one point to plot.
    pub fn new(window: usize) -> Self {
        let window = window.max(2);
        Self { samples: vec![0.5], window, tick_count: 0 }
    }

    /// Feed a live sample (external-feed mode).
    ///
    /// The value is clamped to `0.0..=1.0` and appended to the rolling buffer;
    /// the oldest sample is dropped once the buffer exceeds `window`.
    pub fn push(&mut self, value: f64) {
        let clamped = value.clamp(0.0, 1.0);
        self.samples.push(clamped);
        let overflow = self.samples.len().saturating_sub(self.window);
        if overflow > 0 {
            self.samples.drain(..overflow);
        }
    }

    /// Advance the sparkline by one tick (demo / self-generated mode).
    ///
    /// Computes the next oscillating sample — a sum of sines with a single base
    /// frequency plus two harmonics and a slow drift, giving one smooth
    /// trending line — and pushes it into the rolling buffer. The app should
    /// call this once per frame.
    pub fn tick(&mut self) {
        self.tick_count = self.tick_count.wrapping_add(1);
        let value = Self::oscillator(self.tick_count as f64);
        self.push(value);
    }

    /// Deterministic single-trace oscillator producing a value in `0.0..=1.0`.
    ///
    /// One base frequency (no per-trace index, unlike
    /// [`SpectrumBarsState::oscillator`](crate::SpectrumBarsState::oscillator))
    /// plus two harmonics and a slow drift, so the line reads as one smooth
    /// trending waveform.
    fn oscillator(t: f64) -> f64 {
        // Single base angular frequency (radians/sample).
        let base = 0.35;
        // Two harmonics + a slow drift, normalized to roughly [-1, 1].
        let raw = (base * t).sin() * 0.6
            + (base * 2.3 * t).sin() * 0.25
            + (0.05 * t).sin() * 0.15;
        // Map [-1, 1] → [0, 1] and clamp for safety.
        let mapped = 0.5 + raw * 0.5;
        mapped.clamp(0.0, 1.0)
    }

    /// The latest sample (`0.0` if the buffer is empty).
    pub fn value(&self) -> f64 {
        self.samples.last().copied().unwrap_or(0.0)
    }

    /// Number of samples currently held in the rolling buffer.
    pub fn sample_count(&self) -> usize {
        self.samples.len()
    }

    /// Current tick counter (mainly useful for tests / diagnostics).
    pub fn tick_count(&self) -> u64 {
        self.tick_count
    }
}

/// Map a value to its level's CSS class name (same thresholds as
/// [`EnergyGauge`](crate::EnergyGauge): ≥0.6 ok, ≥0.3 warn, else alert).
fn level_class(value: f64) -> &'static str {
    if value >= 0.6 {
        "ok"
    } else if value >= 0.3 {
        "warn"
    } else {
        "alert"
    }
}

impl StatefulWidget for Sparkline {
    type State = SparklineState;

    fn render(self, area: Rect, buf: &mut Buffer, state: &mut Self::State) {
        // Guard zero-size areas — nothing to draw.
        if area.width == 0 || area.height == 0 {
            return;
        }

        let sheet = self.theme.stylesheet();
        let mut scratch = ComputeScratch::new();

        // Base node carries the chart background; `Spark.grid` the (hidden) grid.
        let base_style = sheet
            .compute_with(&NodeRef::new("Spark"), None, &mut scratch)
            .to_style();
        let chart_bg = base_style.bg;

        // Resolve the level styles once so the line color can react to the
        // latest reading without re-running the cascade per cell.
        let ok_style = sheet
            .compute_with(&NodeRef::new("Spark").classes(&["ok"]), None, &mut scratch)
            .to_style();
        let warn_style = sheet
            .compute_with(&NodeRef::new("Spark").classes(&["warn"]), None, &mut scratch)
            .to_style();
        let alert_style = sheet
            .compute_with(&NodeRef::new("Spark").classes(&["alert"]), None, &mut scratch)
            .to_style();

        // The line color is driven by the latest sample's level. If the CSS
        // rule lacks an fg, fall back to the palette token for that level so
        // the line is never invisible.
        let latest = state.value();
        let palette = self.theme.palette();
        let line_style = match level_class(latest) {
            "ok" => ok_style.fg.unwrap_or(palette.ok.color()),
            "warn" => warn_style.fg.unwrap_or(palette.warn.color()),
            _ => alert_style.fg.unwrap_or(palette.alert.color()),
        };
        let line_style = Style::default().fg(line_style);

        // Build the dataset from the rolling buffer: one (x, y) point per
        // sample, x ranging over the sample indices.
        let data: Vec<(f64, f64)> = state
            .samples
            .iter()
            .enumerate()
            .map(|(idx, &v)| (idx as f64, v))
            .collect();

        let window_f = self.window as f64;
        let dataset = Dataset::default()
            .marker(Marker::Braille)
            .graph_type(self.shape.graph_type())
            .style(line_style)
            .data(&data);

        // Hidden axes (no titles, no labels) — just bounds, so the chart reads
        // as a clean borderless sparkline. ratatui 0.30 carries bounds on the
        // Axis, not on Chart directly.
        let x_axis = Axis::default().bounds([0.0, window_f]);
        let y_axis = Axis::default().bounds([0.0, 1.0]);

        let mut chart = Chart::new(vec![dataset])
            .block(Block::new())
            .x_axis(x_axis)
            .y_axis(y_axis);
        if let Some(bg) = chart_bg {
            chart = chart.style(Style::default().bg(bg));
        }

        // `Chart: Widget`, render by value.
        chart.render(area, buf);

        // Optional right-aligned value readout in the top-right cells.
        if self.show_value {
            let readout = format!("{:3.0}%", latest * 100.0);
            let chars: Vec<&str> = readout.split("").filter(|s| !s.is_empty()).collect();
            let len = chars.len() as u16;
            if area.width >= len && area.height >= 1 {
                let start_x = area.x + area.width - len;
                let y = area.y;
                for (i, ch) in chars.iter().enumerate() {
                    let x = start_x + i as u16;
                    if x < area.x + area.width {
                        buf[(x, y)].set_symbol(ch).set_style(line_style);
                    }
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ratatui::layout::Rect;

    const W: u16 = 40;
    const H: u16 = 5;

    /// Render the widget (driving the oscillator for `ticks` frames) into a
    /// fresh buffer and return it.
    fn render(
        window: usize,
        shape: SparkShape,
        theme: Theme,
        ticks: u64,
        width: u16,
        height: u16,
    ) -> (Buffer, SparklineState) {
        let mut buf = Buffer::empty(Rect::new(0, 0, width, height));
        let widget = Sparkline::new().window(window).shape(shape).theme(theme);
        let mut state = SparklineState::new(window);
        for _ in 0..ticks {
            state.tick();
        }
        StatefulWidget::render(widget, Rect::new(0, 0, width, height), &mut buf, &mut state);
        (buf, state)
    }

    /// True if the buffer has at least one non-space, non-blank cell.
    fn non_blank(buf: &Buffer) -> bool {
        buf.content.iter().any(|c| c.symbol() != " ")
    }

    #[test]
    fn renders_without_panicking_after_ticks() {
        let (buf, _) = render(64, SparkShape::Line, Theme::Cyberpunk, 40, W, H);
        assert!(non_blank(&buf), "expected non-blank cells after rendering");
    }

    #[test]
    fn zero_area_does_not_panic() {
        let widget = Sparkline::new().window(20).theme(Theme::DeepSpace);
        let mut state = SparklineState::new(20);
        let mut buf = Buffer::empty(Rect::ZERO);
        // Must be a no-op, not a panic.
        StatefulWidget::render(widget, Rect::ZERO, &mut buf, &mut state);
    }

    #[test]
    fn tick_advances_clock_and_grows_samples() {
        let mut state = SparklineState::new(16);
        let before = state.tick_count();
        // After construction the buffer holds one baseline sample.
        assert_eq!(state.sample_count(), 1);
        state.tick();
        assert_eq!(state.tick_count(), before + 1);
        assert_eq!(state.sample_count(), 2);
        // Grow up to the window cap.
        for _ in 0..32 {
            state.tick();
        }
        assert_eq!(state.sample_count(), 16, "samples must cap at the window");
        assert!(state.tick_count() > before);
    }

    #[test]
    fn push_clamps_and_caps_window() {
        let mut state = SparklineState::new(4);
        // Over-range values clamp into [0, 1].
        state.push(999.0);
        assert_eq!(state.value(), 1.0);
        state.push(-50.0);
        assert_eq!(state.value(), 0.0);
        // Overflow beyond the window is trimmed.
        state.push(0.2);
        state.push(0.3);
        state.push(0.4);
        assert!(state.sample_count() <= 4, "rolling buffer must respect the window cap");
        assert_eq!(state.sample_count(), 4);
    }

    #[test]
    fn oscillator_stays_in_range() {
        for t in 0..2000_u32 {
            let v = SparklineState::oscillator(t as f64);
            assert!(
                (0.0..=1.0).contains(&v),
                "oscillator out of range: t={t} v={v}"
            );
        }
    }

    #[test]
    fn value_returns_latest_or_zero() {
        let mut state = SparklineState::new(8);
        state.push(0.42);
        assert_eq!(state.value(), 0.42);
        // latest is the most recent push.
        state.push(0.7);
        assert_eq!(state.value(), 0.7);
        // An empty state reports 0.0.
        let empty = SparklineState { samples: Vec::new(), window: 8, tick_count: 0 };
        assert_eq!(empty.value(), 0.0);
    }

    #[test]
    fn shape_variants_render_without_panicking() {
        for shape in [SparkShape::Line, SparkShape::Block, SparkShape::Dot] {
            let (buf, _) = render(32, shape, Theme::Cyberpunk, 20, W, H);
            assert!(non_blank(&buf), "shape {shape:?} should render non-blank cells");
        }
    }

    #[test]
    fn builder_setters_work() {
        let w = Sparkline::new()
            .window(32)
            .shape(SparkShape::Dot)
            .theme(Theme::Weyland)
            .show_value(false);
        assert_eq!(w.window, 32);
        assert_eq!(w.shape, SparkShape::Dot);
        assert_eq!(w.theme, Theme::Weyland);
        assert!(!w.show_value);
    }

    #[test]
    fn default_is_cyberpunk() {
        let w = Sparkline::default();
        assert_eq!(w.window, 64);
        assert_eq!(w.theme, Theme::Cyberpunk);
        assert!(w.show_value);
    }

    #[test]
    fn default_shape_is_line() {
        assert_eq!(SparkShape::default(), SparkShape::Line);
        assert_eq!(Sparkline::default().shape, SparkShape::Line);
    }

    #[test]
    fn window_clamps_to_two() {
        assert_eq!(Sparkline::new().window(0).window, 2);
        assert_eq!(Sparkline::new().window(1).window, 2);
        assert_eq!(SparklineState::new(0).window, 2);
    }

    #[test]
    fn graph_type_mapping() {
        assert_eq!(SparkShape::Line.graph_type(), GraphType::Line);
        assert_eq!(SparkShape::Block.graph_type(), GraphType::Bar);
        assert_eq!(SparkShape::Dot.graph_type(), GraphType::Scatter);
    }

    #[test]
    fn show_value_false_skips_readout() {
        // With the readout off, the top-right cell should remain untouched by
        // the overlay (still blank space in a tiny area).
        let mut buf = Buffer::empty(Rect::new(0, 0, W, 1));
        let widget = Sparkline::new().window(16).show_value(false).theme(Theme::Cyberpunk);
        let mut state = SparklineState::new(16);
        for _ in 0..10 {
            state.tick();
        }
        StatefulWidget::render(widget, Rect::new(0, 0, W, 1), &mut buf, &mut state);
        // No assertion on content beyond "does not panic"; covered by other tests.
        let _ = non_blank(&buf);
    }
}
