//! **StripChart** — multi-channel rolling oscilloscope (hospital-monitor /
//! telemetry style).
//!
//! `N` independent channels are stacked vertically; each channel gets its own
//! small rolling trace that scrolls leftward as new samples arrive, exactly
//! like the waveforms on a vital-signs monitor or a telemetry strip recorder.
//!
//! ## Spec
//! - The area is split into `channels` equal horizontal strips
//!   (`Layout::vertical`); each strip holds one mini `Chart` plotting a single
//!   channel's rolling buffer of `0.0..=1.0` samples against time.
//! - Each mini-chart uses a borderless `Block`, hidden axes,
//!   `x_bounds = [0, window]`, `y_bounds = [0, 1]`, and a `Marker::Braille`
//!   dataset whose `GraphType` is selected by [`StripShape`] (`Line` default,
//!   `Fill`, or `Bar`).
//!
//! ## Implementation notes
//! - Stateful [`StatefulWidget`]; per-channel rolling sample buffers live in
//!   [`StripChartState`], pushed each tick (or self-generated by `tick()`).
//! - Rendered with one ratatui `Chart` per channel (rather than a single shared
//!   `Chart` with overlapping `Dataset`s as in
//!   [`BiometricChart`](crate::BiometricChart)). The contrast:
//!     - **BiometricChart** — one shared plot, several traces overlapping on
//!       the same axes (a compound vital-signs readout).
//!     - **StripChart** — one *separate* mini-plot per channel, stacked
//!       vertically (a telemetry strip recorder).
//!
//!   Each channel's mini-`Chart` is a stateless `Widget`, rendered by value
//!   into its strip's sub-rect via `Layout::vertical`.
//! - Colors come from the theme's CSS cascade, not the raw palette. The base
//!   `Strip` node carries the strip background (panel); the grid/divider color
//!   resolves from `Strip.grid` (fallback `palette.muted`); and each channel's
//!   trace color resolves from the `Strip.ch0..4` rules (channels ≥5 cycle back
//!   to `ch0`):
//!     - channel 0 → `Strip.ch0` (var `--accent`)
//!     - channel 1 → `Strip.ch1` (var `--accent2`)
//!     - channel 2 → `Strip.ch2` (var `--ok`)
//!     - channel 3 → `Strip.ch3` (var `--warn`)
//!     - channel 4 → `Strip.ch4` (var `--alert`)
//!
//!   Should a `chN` rule be absent, the renderer falls back to cycling the raw
//!   palette tokens `accent / accent2 / ok / warn / alert`.
//! - Two data-feed modes:
//!     1. **External**: the app calls [`StripChartState::push`] to feed live
//!        samples per channel.
//!     2. **Self-generated (demo mode)**: the app calls [`StripChartState::tick`]
//!        each frame and the state advances its own deterministic oscillator
//!        (a distinct base frequency per channel, mirroring
//!        [`SpectrumBarsState`](crate::SpectrumBarsState)'s per-index
//!        oscillator), so every channel reads differently. The demo uses this
//!        mode.
//! - The [`StripShape::Fill`] variant: ratatui's `Chart` has no true area-fill,
//!   so `Fill` draws the channel as a braille **line** *plus* a second
//!   `GraphType::Bar` dataset from the baseline (`y = 0`) up to each sample.
//!   The two datasets share the same channel color, producing a filled-silhouette
//!   look beneath the line. (`Line` is just the line; `Bar` is just the bars.)
//!
//! # Example
//!
//! ```no_run
//! use ratatui_sci_fi::{StripChart, StripChartState, Theme};
//!
//! let mut state = StripChartState::new(4, 80);
//! let chart = StripChart::new().channels(4).window(80).theme(Theme::Cyberpunk);
//! // In the event loop: state.tick(); each frame, then render the chart.
//! ```

use ratatui::{
    buffer::Buffer,
    layout::{Constraint, Layout, Rect},
    style::Style,
    symbols::Marker,
    widgets::{Axis, Block, Chart, Dataset, GraphType, StatefulWidget, Widget},
};
use ratatui_style::{ComputeScratch, NodeRef};

use crate::Theme;

/// Y-axis range each channel trace is plotted against. Samples are clamped to it.
const Y_MIN: f64 = 0.0;
const Y_MAX: f64 = 1.0;

/// Visual form of a [`StripChart`] channel trace.
///
/// Selects the per-channel ratatui [`GraphType`] (and, for [`StripShape::Fill`],
/// whether an extra baseline dataset is drawn). Colors stay on the CSS cascade
/// (`Strip` / `Strip.chN` / `Strip.grid`), untouched by this enum. The
/// [`StripShape::Line`] default gives the classic connected-oscilloscope look.
///
/// The shape is CONFIG — it lives on the widget struct, never on `…State` (see
/// convention #5 at the crate root).
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum StripShape {
    /// Braille connected line per channel (`GraphType::Line`). This is the
    /// default oscilloscope look.
    #[default]
    Line,
    /// Filled area per channel. ratatui's `Chart` has no true fill, so `Fill`
    /// draws the channel as a braille **line** plus a second `GraphType::Bar`
    /// dataset from the baseline (`y = 0`) up to each sample, both in the
    /// channel color — producing a filled-silhouette beneath the trace.
    Fill,
    /// Braille columns per channel (`GraphType::Bar`).
    Bar,
}

impl StripShape {
    /// The primary ratatui [`GraphType`] this shape draws a channel with.
    ///
    /// `Fill` is drawn as a `Line` (its area silhouette is added as a second
    /// `Bar` dataset by the renderer).
    #[must_use]
    pub const fn graph_type(self) -> GraphType {
        match self {
            Self::Line | Self::Fill => GraphType::Line,
            Self::Bar => GraphType::Bar,
        }
    }
}

/// A multi-channel rolling oscilloscope (telemetry strip recorder).
///
/// Immutable config lives here (`channels`, `window`, `shape`, `theme`);
/// everything that changes per frame lives in [`StripChartState`].
#[derive(Debug, Clone)]
pub struct StripChart {
    /// Number of stacked channels (default `4`, clamped ≥1).
    pub channels: usize,
    /// Horizontal sample-window width (number of points kept per channel).
    pub window: usize,
    /// Per-channel trace form. Defaults to [`StripShape::Line`].
    pub shape: StripShape,
    /// Theme whose palette drives all colors via CSS cascade. Default
    /// [`Theme::Cyberpunk`].
    pub theme: Theme,
}

impl Default for StripChart {
    fn default() -> Self {
        Self {
            channels: 4,
            window: 80,
            shape: StripShape::default(),
            theme: Theme::Cyberpunk,
        }
    }
}

impl StripChart {
    /// Build a strip chart with default config (4 channels, window 80, Line).
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the number of stacked channels (clamped to at least 1). Builder.
    #[must_use]
    pub fn channels(mut self, n: usize) -> Self {
        self.channels = n.max(1);
        self
    }

    /// Set the sample-window width (clamped to at least 2). Builder.
    #[must_use]
    pub fn window(mut self, n: usize) -> Self {
        self.window = n.max(2);
        self
    }

    /// Set the per-channel trace form (see [`StripShape`]). Builder.
    #[must_use]
    pub fn shape(mut self, s: StripShape) -> Self {
        self.shape = s;
        self
    }

    /// Replace the theme (builder). Default is [`Theme::Cyberpunk`].
    #[must_use]
    pub fn theme(mut self, t: Theme) -> Self {
        self.theme = t;
        self
    }
}

/// Mutable state for [`StripChart`].
///
/// Holds a rolling sample buffer per channel (length capped at `window`) plus a
/// tick counter that drives the self-generated oscillator. The app advances it
/// every frame via [`Self::tick`] (demo mode) or feeds live samples via
/// [`Self::push`] (external mode).
#[derive(Debug, Clone)]
pub struct StripChartState {
    /// Per-channel rolling sample buffers; each `Vec<f64>` holds the most recent
    /// up-to-`window` samples (in `0.0..=1.0`), oldest first.
    buffers: Vec<Vec<f64>>,
    /// Configured window length (max samples kept per channel).
    window: usize,
    /// Animation clock, advanced each tick; used by the self-generated
    /// oscillator when no external data is pushed.
    tick_count: u64,
}

impl Default for StripChartState {
    fn default() -> Self {
        Self::new(4, 80)
    }
}

impl StripChartState {
    /// Build state sized for `channels` channels and a `window`-sample rolling
    /// buffer (clamped to at least 1 channel and a window of at least 2).
    /// Buffers start seeded with one mid-range baseline so the first frame
    /// isn't empty.
    pub fn new(channels: usize, window: usize) -> Self {
        let channels = channels.max(1);
        let window = window.max(2);
        // Seed each buffer with one mid-range baseline so the first render has
        // at least one point per channel to plot.
        let baseline = (Y_MIN + Y_MAX) / 2.0;
        let buffers = (0..channels).map(|_| vec![baseline]).collect();
        Self { buffers, window, tick_count: 0 }
    }

    /// Feed a live sample for `channel_index` (external-feed mode).
    ///
    /// The value is clamped to `[Y_MIN, Y_MAX]` (`0.0..=1.0`) and appended to
    /// that channel's rolling buffer; the oldest sample is dropped once the
    /// buffer exceeds `window`. Out-of-range indices are ignored.
    pub fn push(&mut self, channel_index: usize, value: f64) {
        let Some(buf) = self.buffers.get_mut(channel_index) else {
            return;
        };
        let clamped = value.clamp(Y_MIN, Y_MAX);
        crate::widgets::util::capped_push(buf, clamped, self.window);
    }

    /// Advance every channel's trace by one tick (demo / self-generated mode).
    ///
    /// Computes the next oscillating sample for every channel — a sum of sines
    /// with a distinct base frequency per channel plus a couple of harmonics
    /// and a slow drift (mirroring
    /// [`SpectrumBarsState`](crate::SpectrumBarsState)'s per-index oscillator so
    /// channels read differently) — and pushes it into each rolling buffer. The
    /// app should call this once per frame.
    pub fn tick(&mut self) {
        self.tick_count = self.tick_count.wrapping_add(1);
        let t = self.tick_count as f64;
        for (i, buf) in self.buffers.iter_mut().enumerate() {
            let value = Self::oscillator(i, t);
            crate::widgets::util::capped_push(buf, value, self.window);
        }
    }

    /// Deterministic per-channel oscillator producing a value in
    /// `[Y_MIN, Y_MAX]` (`0.0..=1.0`).
    ///
    /// Each channel gets a distinct base frequency (mirroring
    /// [`SpectrumBarsState`](crate::SpectrumBarsState)'s per-index frequency) so
    /// neighboring channels read differently; a couple of harmonics plus a slow
    /// drift create the lively oscilloscope-like shape.
    fn oscillator(channel: usize, t: f64) -> f64 {
        // Distinct base angular frequency per channel (radians/sample).
        let base = 0.30 + 0.21 * (channel as f64 + 1.0);
        // Phase offset so neighboring channels don't align.
        let phase = (channel as f64) * 0.7;
        // Two harmonics + a slow drift, normalized to roughly [-1, 1].
        let raw = (base * t + phase).sin() * 0.55
            + (base * 2.1 * t + phase).sin() * 0.30
            + (0.04 * t + phase * 1.3).sin() * 0.15;
        // Map [-1, 1] → [0, 1] and clamp for safety.
        let mapped = 0.5 + raw * 0.5;
        mapped.clamp(Y_MIN, Y_MAX)
    }

    /// The latest sample for `channel_index` (`0.0` if the buffer is empty or
    /// the index is out of range).
    #[must_use]
    pub fn value(&self, channel_index: usize) -> f64 {
        self.buffers
            .get(channel_index)
            .and_then(|b| b.last().copied())
            .unwrap_or(Y_MIN)
    }

    /// Number of samples currently held for `channel_index` (`0` if the index is
    /// out of range).
    #[must_use]
    pub fn sample_count(&self) -> usize {
        // All buffers share the same cap and are seeded identically, so report
        // the first buffer's length as the representative count (0 if empty).
        self.buffers.first().map_or(0, Vec::len)
    }

    /// Current tick counter (mainly useful for tests / diagnostics).
    #[must_use]
    pub fn tick_count(&self) -> u64 {
        self.tick_count
    }
}

/// Resolve the channel-trace style for channel `i` from the `Strip.chN` cascade
/// rule (cycling `ch0..ch4`), falling back to the raw palette tokens if a rule
/// is absent. Returns the resolved ratatui [`Style`].
fn channel_style(
    sheet: &ratatui_style::Stylesheet,
    i: usize,
    palette: &crate::Palette,
    scratch: &mut ComputeScratch,
) -> Style {
    // Cycle ch0..ch4 so channel ≥5 wraps back to ch0.
    let cls = format!("ch{}", i % 5);
    let computed =
        sheet.compute_with(&NodeRef::new("Strip").classes(&[cls.as_str()]), None, scratch).to_style();
    if computed.fg.is_some() {
        return computed;
    }
    // Fallback: cycle the raw palette tokens accent / accent2 / ok / warn / alert.
    let colors = [
        palette.accent.color(),
        palette.accent2.color(),
        palette.ok.color(),
        palette.warn.color(),
        palette.alert.color(),
    ];
    Style::default().fg(colors[i % colors.len()])
}

impl StatefulWidget for StripChart {
    type State = StripChartState;

    fn render(self, area: Rect, buf: &mut Buffer, state: &mut Self::State) {
        // Guard zero-size areas — nothing to draw.
        if area.width == 0 || area.height == 0 {
            return;
        }

        let sheet = self.theme.stylesheet();
        let palette = self.theme.palette();
        let mut scratch = ComputeScratch::new();

        // Base `Strip` node carries the strip background (panel).
        let base_style = sheet
            .compute_with(&NodeRef::new("Strip"), None, &mut scratch)
            .to_style();
        let strip_bg = base_style.bg;

        // Grid/divider color from `Strip.grid` (fallback `palette.muted`).
        let grid_style = {
            let g = sheet
                .compute_with(&NodeRef::new("Strip").classes(&["grid"]), None, &mut scratch)
                .to_style();
            if g.fg.is_some() {
                g
            } else {
                Style::default().fg(palette.muted.color())
            }
        };
        // Reuse the grid color as the (hidden) axis style so any axis rendering
        // ratatui performs is themed consistently.
        let axis_style = grid_style;

        // Pre-resolve every channel's trace style once.
        let channel_styles: Vec<Style> =
            (0..self.channels).map(|i| channel_style(sheet, i, &palette, &mut scratch)).collect();

        // Split the area into `channels` equal horizontal strips.
        let constraints = std::iter::repeat_n(Constraint::Fill(1), self.channels);
        let strips = Layout::vertical(constraints).split(area);

        let window_f = self.window as f64;

        for (i, strip_rect) in strips.iter().enumerate() {
            if strip_rect.width == 0 || strip_rect.height == 0 {
                continue;
            }

            // Map this channel's samples to (x, y) pairs, right-aligned so the
            // waveform scrolls in from the right (mirror BiometricChart).
            let samples = state.buffers.get(i).map(Vec::as_slice).unwrap_or(&[]);
            let pts: Vec<(f64, f64)> = if !samples.is_empty() {
                let n = samples.len();
                let start = window_f - (n as f64 - 1.0).max(0.0) - 1.0;
                samples
                    .iter()
                    .enumerate()
                    .map(|(idx, &v)| (start + (idx as f64), v))
                    .collect()
            } else {
                Vec::new()
            };

            let trace_color = channel_styles[i];
            let mut datasets: Vec<Dataset<'_>> = Vec::new();

            if matches!(self.shape, StripShape::Fill) {
                // Line + a baseline-up Bar silhouette for a filled-area look.
                datasets.push(
                    Dataset::default()
                        .name(format!("ch{i}"))
                        .data(&pts)
                        .marker(Marker::Braille)
                        .graph_type(GraphType::Line)
                        .style(trace_color),
                );
                // Baseline-up bar silhouette: for each sample draw a vertical
                // bar from y=0 up to the sample value. ratatui's `GraphType::Bar`
                // already renders a vertical column at each x, so feeding the
                // same (x, value) points with `Bar` gives the fill beneath the
                // line.
                datasets.push(
                    Dataset::default()
                        .name(format!("ch{i}_fill"))
                        .data(&pts)
                        .marker(Marker::Braille)
                        .graph_type(GraphType::Bar)
                        .style(trace_color),
                );
            } else {
                datasets.push(
                    Dataset::default()
                        .name(format!("ch{i}"))
                        .data(&pts)
                        .marker(Marker::Braille)
                        .graph_type(self.shape.graph_type())
                        .style(trace_color),
                );
            }

            // Hidden axes: bounds only, empty labels (mirror BiometricChart's
            // `Axis::default().bounds([...])` shape, with no visible labels).
            let x_axis = Axis::default().bounds([0.0, window_f]).style(axis_style);
            let y_axis = Axis::default().bounds([Y_MIN, Y_MAX]).style(axis_style);

            let mut chart_builder = Chart::new(datasets).x_axis(x_axis).y_axis(y_axis);
            if let Some(bg) = strip_bg {
                chart_builder = chart_builder.style(Style::default().bg(bg));
            }
            let chart = chart_builder.block(Block::new());

            // `Chart: Widget`, render by value into this channel's strip.
            chart.render(*strip_rect, buf);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ratatui::layout::Rect;

    const W: u16 = 60;
    const H: u16 = 16;

    /// Render the widget (driving the oscillator for `ticks` frames) into a
    /// fresh buffer and return it.
    fn render(
        channels: usize,
        window: usize,
        shape: StripShape,
        theme: Theme,
        ticks: u64,
        width: u16,
        height: u16,
    ) -> (Buffer, StripChartState) {
        let mut buf = Buffer::empty(Rect::new(0, 0, width, height));
        let widget = StripChart::new()
            .channels(channels)
            .window(window)
            .shape(shape)
            .theme(theme);
        let mut state = StripChartState::new(channels, window);
        for _ in 0..ticks {
            state.tick();
        }
        StatefulWidget::render(widget, Rect::new(0, 0, width, height), &mut buf, &mut state);
        (buf, state)
    }

    /// True if the buffer has at least one non-space, non-blank cell.
    fn non_blank(buf: &Buffer) -> bool {
        buf.content.iter().any(|c| c.symbol() != " ")
    }

    #[test]
    fn renders_without_panicking_after_ticks() {
        let (buf, _) = render(4, 80, StripShape::Line, Theme::Cyberpunk, 40, W, H);
        assert!(non_blank(&buf), "expected non-blank cells after rendering");
    }

    #[test]
    fn zero_area_does_not_panic() {
        let widget = StripChart::new().channels(4).window(20).theme(Theme::DeepSpace);
        let mut state = StripChartState::new(4, 20);
        let mut buf = Buffer::empty(Rect::ZERO);
        // Must be a no-op, not a panic.
        StatefulWidget::render(widget, Rect::ZERO, &mut buf, &mut state);
    }

    #[test]
    fn tick_advances_clock_and_grows_buffers() {
        let mut state = StripChartState::new(4, 16);
        let before = state.tick_count();
        // After construction each buffer holds one baseline sample.
        assert_eq!(state.buffers.len(), 4);
        assert_eq!(state.buffers[0].len(), 1);
        assert_eq!(state.sample_count(), 1);
        state.tick();
        assert_eq!(state.tick_count(), before + 1);
        // Each channel's buffer grew by exactly one sample.
        for b in &state.buffers {
            assert_eq!(b.len(), 2);
        }
        assert_eq!(state.sample_count(), 2);

        // Buffers grow until the window cap, then hold steady.
        for _ in 0..32 {
            state.tick();
        }
        for b in &state.buffers {
            assert!(b.len() <= 16, "rolling buffer must respect the window cap");
        }
        assert_eq!(state.sample_count(), 16);
    }

    #[test]
    fn push_clamps_and_caps_window() {
        let mut state = StripChartState::new(2, 4);
        // Over-range values clamp into [0, 1].
        state.push(0, 999.0);
        assert_eq!(state.buffers[0].last().copied(), Some(1.0));
        state.push(0, -50.0);
        assert_eq!(state.buffers[0].last().copied(), Some(0.0));
        // Overflow beyond the window is trimmed.
        state.push(0, 0.2);
        state.push(0, 0.3);
        state.push(0, 0.4);
        assert!(state.buffers[0].len() <= 4, "rolling buffer must respect the window cap");
        // Out-of-range channel index is ignored (no panic).
        state.push(99, 0.5);
        assert_eq!(state.buffers.len(), 2);
    }

    #[test]
    fn oscillator_stays_in_range() {
        for channel in 0..16_u32 {
            for t in 0..1000_u32 {
                let v = StripChartState::oscillator(channel as usize, t as f64);
                assert!(
                    (Y_MIN..=Y_MAX).contains(&v),
                    "oscillator out of range: channel={channel} t={t} v={v}"
                );
            }
        }
    }

    #[test]
    fn value_returns_latest_or_zero() {
        let mut state = StripChartState::new(2, 8);
        state.push(0, 0.42);
        assert_eq!(state.value(0), 0.42);
        // Out-of-range channel → 0.0, no panic.
        assert_eq!(state.value(99), Y_MIN);
    }

    #[test]
    fn shape_variants_render_without_panicking() {
        for shape in [StripShape::Line, StripShape::Fill, StripShape::Bar] {
            let (buf, _) = render(4, 60, shape, Theme::Weyland, 30, W, H);
            assert!(
                non_blank(&buf),
                "expected non-blank cells for shape {shape:?}"
            );
        }
    }

    #[test]
    fn builder_setters_work() {
        let w = StripChart::new()
            .channels(6)
            .window(100)
            .shape(StripShape::Bar)
            .theme(Theme::Fallout);
        assert_eq!(w.channels, 6);
        assert_eq!(w.window, 100);
        assert_eq!(w.shape, StripShape::Bar);
        assert_eq!(w.theme, Theme::Fallout);
    }

    #[test]
    fn default_is_cyberpunk() {
        let w = StripChart::default();
        assert_eq!(w.channels, 4);
        assert_eq!(w.window, 80);
        assert_eq!(w.theme, Theme::Cyberpunk);
    }

    #[test]
    fn default_shape_is_line() {
        assert_eq!(StripChart::default().shape, StripShape::Line);
        assert_eq!(StripShape::default(), StripShape::Line);
        // graph_type mapping sanity.
        assert_eq!(StripShape::Line.graph_type(), GraphType::Line);
        assert_eq!(StripShape::Fill.graph_type(), GraphType::Line);
        assert_eq!(StripShape::Bar.graph_type(), GraphType::Bar);
    }

    #[test]
    fn channel_clamps_to_at_least_one() {
        assert_eq!(StripChart::new().channels(0).channels, 1);
        let mut state = StripChartState::new(0, 10);
        assert_eq!(state.buffers.len(), 1);
        // ticking the single channel must not panic.
        state.tick();
        assert_eq!(state.buffers[0].len(), 2);
    }

    #[test]
    fn window_clamps_to_at_least_two() {
        assert_eq!(StripChart::new().window(0).window, 2);
        assert_eq!(StripChart::new().window(1).window, 2);
    }

    #[test]
    fn render_across_many_ticks_does_not_panic() {
        // Smoke test: render repeatedly across ticks, ensuring stability for
        // every shape.
        for shape in [StripShape::Line, StripShape::Fill, StripShape::Bar] {
            let mut state = StripChartState::new(4, 40);
            let mut buf = Buffer::empty(Rect::new(0, 0, W, H));
            for _ in 0..120 {
                state.tick();
                let widget =
                    StripChart::new().channels(4).window(40).shape(shape).theme(Theme::Fallout);
                StatefulWidget::render(widget, Rect::new(0, 0, W, H), &mut buf, &mut state);
            }
            assert!(non_blank(&buf), "expected content for shape {shape:?}");
        }
    }
}
